### ISSUE TITLE
Update `index.md` to match `README.md`

### ISSUE THREAD

**Issue by e3m3** [ILLIXR/illixr.github.io#4]
The content of these two pages should be the same.

**Comment by mhuzai** [comment]
The copy that Sarita requested was from `index.md` to `README.md`. Why is `index.md` being updated here?

**Comment by e3m3** [comment]
> The copy that Sarita requested was from index.md to README.md. Why is index.md being updated here?

This copy had old formatting, and some other outdated text. This copy should now have the same content and formatting except:
- The additional acknowledgement for the website.
- The file header.
- The badges.
